name: Primer workflow

on: push

jobs:
  primer_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Prueba de workflow"

      - name: Obtener código
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: ej1
        run: |
          pip install pytest
          pytest test.py

