name: Primer workflow

on: push

jobs:
  primer_workflow:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      
    steps:
      - name: Mostrar mensaje
        run: echo "Prueba de workflow"

      - name: Obtener código
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: Lint ej2
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ulopeznovoa/as-demo-2024

