name: Primer workflow

on: push

jobs:
  primer_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar mensaje
        run: echo "Prueba de workflow"

      - name: Obtener código
        uses: actions/checkout@v4

      - name: Probar código
        run: python3 main.py

      - name: Crear imagen Docker
        run: docker build -t ulopeznovoa/as-demo-2024 .

      - name: Probar contenedor 
        run: docker run ulopeznovoa/as-demo-2024

